// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB11BIpO0HPFKhOkiNRA-CTf1mq0O_LoW8',
    appId: '1:162779619925:web:dd32a3c53060903a35aadc',
    messagingSenderId: '162779619925',
    projectId: 'elabv02',
    authDomain: 'elabv02.firebaseapp.com',
    storageBucket: 'elabv02.appspot.com',
    measurementId: 'G-361T8GMZ19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrX239eJnHu-vt5eKiAvnTwPlAn8UAom4',
    appId: '1:162779619925:android:e14d8d14e294566435aadc',
    messagingSenderId: '162779619925',
    projectId: 'elabv02',
    storageBucket: 'elabv02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABKya0xjcitESJNjlIL4zyK7ZwUytR694',
    appId: '1:162779619925:ios:1633f37f221036b435aadc',
    messagingSenderId: '162779619925',
    projectId: 'elabv02',
    storageBucket: 'elabv02.appspot.com',
    iosBundleId: 'com.example.elabv01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABKya0xjcitESJNjlIL4zyK7ZwUytR694',
    appId: '1:162779619925:ios:1633f37f221036b435aadc',
    messagingSenderId: '162779619925',
    projectId: 'elabv02',
    storageBucket: 'elabv02.appspot.com',
    iosBundleId: 'com.example.elabv01',
  );
}
